### ISSUE TITLE
Resize in flexbox

### ISSUE THREAD

**Issue by zwiebelspaetzle** [opensheetmusicdisplay/opensheetmusicdisplay#331]
I'm trying to use osmd within a flexbox setup, and have osmd resize appropriately when the window size changes.  Osmd will grow as expected when the window get wider, but will not shrink when the window gets more narrow.

I suspect this has to do with the `width` attribute in the `canvas`/`svg` element.

I've posted an example at http://oldtimetunebook.com/test.html.

Here is the markup:
```html
<html>
    <head>
        <style>
            body {
                display: flex;
            }

            #left {
                background-color: #fdd;
                flex-basis: 10rem;
            }

            #right {
                background-color: #ddf;
                flex-basis: auto;
                flex-grow: 1;
                flex-shrink: 1;
            }
        </style>
        <script src="./opensheetmusicdisplay.min.js"></script>
    </head>

    <body>
        <div id="left">Left</div>
        <div id="right"></div>
    </body>
    <script>
        var osmd = new opensheetmusicdisplay.OpenSheetMusicDisplay("right");
        osmd.load("./MozaVeilSample.xml").then(
            function() {
                osmd.zoom = 0.8;
                osmd.render();
                window.addEventListener("resize", () => {
                    osmd.render();
                });
            }
        );
    </script>
</html>
```

Thanks!

**Comment by sschmidTU** [comment]
This also happens for mobile browsers (open Chrome Developer Tools -> Ctrl-Shift-M).
We might need to [use Media Queries](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries).
Maybe you would need to handle the re-rendering of OSMD yourself if you use these kinds of CSS-layouts, but maybe OSMD should be handling it for you.

Thanks for reporting the issue! We are looking into it.

**Comment by bneumann** [comment]
Hi @zwiebelspaetzle. So we found the issue(s), and you can try out if it fixes your problem as well: The resizing is not enabled by default, you can do that by calling 
```javascript
var osmd = new opensheetmusicdisplay.OpenSheetMusicDisplay("right", true);
```
But that alone doesn't do anything because now resizing leaves the containers size the same but only scales down the page. You need to tell the browser that a scaling is also resizing the viewport. To to so add this to your head node ([viewport meta tag](https://developer.mozilla.org/de/docs/Mozilla/Mobile/Viewport_meta_tag))
```html
<meta name="viewport" content="width=device-width, initial-scale=1">
```


So all in all your HTML looks like so:

```html
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
            body {
                display: flex;
            }

            #left {
                background-color: #fdd;
                flex-basis: 10rem;
            }

            #right {
                background-color: #ddf;
                flex-basis: auto;
                flex-grow: 1;
                flex-shrink: 1;
            }
        </style>
        <script src="./opensheetmusicdisplay.min.js"></script>
    </head>

    <body>
        <div id="left">Left</div>
        <div id="right"></div>
    </body>
    <script>
        var osmd = new opensheetmusicdisplay.OpenSheetMusicDisplay("right", true);
        osmd.load("./MozaVeilSample.xml").then(
            function() {
                osmd.zoom = 0.8;
                osmd.render();
                window.addEventListener("resize", () => {
                    osmd.render();
                });
            }
        );
    </script>
</html>
```

Please let me know if that works for you in that flexbox. The other possibility is (if you don't want to have responsivness on your page) to implement the resize method yourself and check for the flexbox css property. But this might be quite tedious.

**Comment by zwiebelspaetzle** [comment]
Unfortunately, it still doesn't work.  Thanks for the suggestions.

**Comment by bneumann** [comment]
@zwiebelspaetzle, do you have something new? I haven't found anything useful so far.
Maybe try using a div instead of a flexbox?

**Comment by zwiebelspaetzle** [comment]
@bneumann  no, I haven't found anything new.   Sorry about the delay.

**Comment by bneumann** [comment]
Hi @zwiebelspaetzle,

we just found a bug in our auto resize code that prevented it from working. We will make another release this week for you to test with. Hopefully we can get your stuff to work.

**Comment by sschmidTU** [comment]
@zwiebelspaetzle the resize fix is merged into develop, maybe you can try it again.
We will release a new version 0.6 soon as well.

**Comment by sschmidTU** [comment]
By the way, you don't need to add an eventHandler for resize in your script to make OSMD render again after resize, our resize handler calls render anyways.

**Comment by zwiebelspaetzle** [comment]
@sschmidTU thanks for the update!
I'm still unable to get the osmd canvas to shrink in the flexbox.  You can see my test run here: https://test.oldtimetunebook.com/test.html

Here is the code:
```
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
            body {
                display: flex;
            }

            #left {
                background-color: #fdd;
                flex-basis: 10rem;
            }

            #right {
                background-color: #ddf;
                flex-basis: auto;
                flex-grow: 1;
                flex-shrink: 1;
            }
        </style>
        <script src="./opensheetmusicdisplay.min.js"></script>
    </head>

    <body>
        <div id="left">Left</div>
        <div id="right"></div>
    </body>
    <script>
        var osmd = new opensheetmusicdisplay.OpenSheetMusicDisplay("right", {autoResize: true});
        osmd.setLogLevel('debug')
        osmd.load("./Cherokee_Shuffle.musicxml").then(
            function() {
                osmd.zoom = 0.8;
                osmd.render();
            }
        );
    </script>
</html>
```

**Comment by sschmidTU** [comment]
@zwiebelspaetzle I think i found a fix:
add `max-width: 98vw;` to `#right` in the css.
This sets the max width in relation to the viewport width, which seems to ignore the part that's not in your scroll selection.
You can customize the '98', it's just that when the window gets very narrow, values closer to 100 will still create a scroll bar.
Should work with most OSMD builds, but to be safe you could build a new one.

I also tried to find a way to disable scrolling altogether, which is frustratingly not easy with HTML.

I thought the recent commit afe253710d4d3cc19ac8f291b440219b57104f77 did the trick, but i think I mistook that for the effect that this css change did.

By the way, we just [released OSMD 0.6.0](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/429), you can find an updated build in our [Github releases](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/releases).
