### ISSUE TITLE
issue with 8va display and missing slur

### ISSUE THREAD

**Issue by misterallx** [opensheetmusicdisplay/opensheetmusicdisplay#490]
Hello! 
Another thanks for the amazing project!

wanted to bring attention to the following. The 8va seems to blend in with the notes, and
in the first option, the last slur is missing. Also, although the 8va line does not reach the harmonic, it assumes it to have been affected by it I guess?
In the second picture, I attempted to make the harmonic a separate voice, and this was the output.
Thanks for your time!
![strange_output](https://user-images.githubusercontent.com/33357194/52979494-e53a4d80-33a3-11e9-9141-48ba04cf5f74.png)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

![strange_output2](https://user-images.githubusercontent.com/33357194/52979497-e79ca780-33a3-11e9-9da1-a6cd46010088.png)

**Comment by bneumann** [comment]
Hi, thanks for posting this bug. First of all out of interest: can you play that? I mean there are percussion notes in between!

Anyways I would like to have a look at the 8va problem. Can you attach the files here so we can try to reproduce the behavior?

**Comment by sschmidTU** [comment]
The diamond notes are harmonics (de: Flageolett) on the violin.
This is an interesting sample, I would also appreciate if you could export it to XML from your notation program and attach it to a comment (need to zip the file first).

This does seem to be a somewhat rare and difficult case for OSMD, because the octaved notes are very high, so the "8va" would need to be very high as well.
It's strange that the slur doesn't display, though.

**Comment by misterallx** [comment]
Thank you for your replies!
It is playable, this is from a known classical violin piece and sschmidTU is correct about the harmonic.
Interestingly, the slur shows up when I force the note stems to be down, but then the issue from the second picture occurs. I am happy to attach the 
XMLs below. 

[8vaXMLs.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/2880654/8vaXMLs.zip)

Thank you!

**Comment by bneumann** [comment]
Hi,
I had a look at your files and fixed the 8va at least it is readable now:
![image](https://user-images.githubusercontent.com/2605131/53286455-12557a00-376f-11e9-9f65-c913a443627e.png)

BUT from the XML I see that our rendering is indeed correct. The 8va end before those fancy chord, harmonics cue note stuff. So if you want it to be under the 8va you need to shift the end.

I will commit the fix but I have to wait for some other commits that are needed for this change.

**Comment by sschmidTU** [comment]
I'm still puzzled that the slur doesn't get displayed.
From a quick glance, i don't know why.
Would have to take a deeper look at VexFlowMusicSheetCalculator.ts:calculateSlurs().

but it's great that the 8va is fixed!

**Comment by bneumann** [comment]
Partially fixed😁 I saw some problems with text collisions that I wanna fix, so leave it open a lil bit longer

**Comment by misterallx** [comment]
@bneumann @sschmidTU  Thank you for the updates and fixes! Will keep it open.

**Comment by bneumann** [comment]
Revisiting old issues right now I found that this has been almost fixed. @misterallx can you have a look at the latest version and confirm that?

**Comment by sschmidTU** [comment]
first sample is fixed:
![image](https://user-images.githubusercontent.com/33069673/89307796-c7cd7200-d671-11ea-8ab0-ad493c65c090.png)

the second sample still has the overly long stems, not sure why that happens.
![image](https://user-images.githubusercontent.com/33069673/89307918-ee8ba880-d671-11ea-874a-49e19518d82f.png)

**Comment by sschmidTU** [comment]
second sample is also fixed:
![image](https://user-images.githubusercontent.com/33069673/142454297-530b2c76-55a2-453f-b405-081a3de367c2.png)
