### ISSUE TITLE
the staffEntry position is wrong with whole rest note

### ISSUE THREAD

**Issue by DavoWU** [opensheetmusicdisplay/opensheetmusicdisplay#616]
![Screen Shot 2019-11-05 at 23 08 38](https://user-images.githubusercontent.com/23088138/68219593-3917c000-0021-11ea-908b-c27e96eac2bb.png)

I found that for whole rest note(probably half rest note as well), the staffEntry is wrong, so that cursor is wrong as well, is there any way to fix it? 
thanks

**Comment by sschmidTU** [comment]
I think this is due to special positioning of (whole) rest notes in Vexflow.
We'll have to see if we can get the correct position from Vexflow, for example from the rest note's bounding box.

**Comment by DavoWU** [comment]
@sschmidTU thanks!! much appreciated

**Comment by DavoWU** [comment]
@sschmidTU
Hi
 I fixed the vexflowStaffEntery with whole rest notes, could I possible update the OSMD thanks

**Comment by sschmidTU** [comment]
duplicate of #609

**Comment by TheBrightestStarInTheNightSky** [comment]
@DavoWU @sschmidTU After I updated the develop branch code, the test found that the problem was not completely solved. In the test muxicxml provided by you, Clementi, m-sonatina op. 36, section 13 of No1 pt.2, section Haydn, section 28 of j-concertante Cello, and my musicxml, the problem still appeared. Screenshots and musicxml I put in the zip
[musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3919777/musicxml.zip)

**Comment by sschmidTU** [comment]
I fixed the whole rest error, see #609.
