### ISSUE TITLE
Stems detach from note heads on window resize

### ISSUE THREAD

**Issue by MilesMorel** [opensheetmusicdisplay/opensheetmusicdisplay#724]
I've noticed that when I resize the window, eighth note heads often detach from their stems. Since OSMD calls render on window resize I'm not sure what I'm missing. Any advice is greatly appreciated!

![image](https://user-images.githubusercontent.com/44449222/79709590-91214680-8290-11ea-8367-a34751c5c4cb.png)

**Comment by matt-uib** [comment]
@sschmidTU this should be fixed according to #655, right?

**Comment by sschmidTU** [comment]
No, this problem is still there.
#655 is probably a fix, we just need to apply it to this situation.
In #655, we recalculate when the zoom has changed.
I guess we also need to recalculate on resize.
Same reasons: Vexflow seems to not recalculate beams when redrawing after a reformat (?).

But first, i'll update Vexflow to 3.0.9 (currently 3.0.4) and see if and what changes.

**Comment by sschmidTU** [comment]
[beam_detach_bug.musicxml.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4516271/beam_detach_bug.musicxml.txt)
![image](https://user-images.githubusercontent.com/33069673/79985907-8f7f9a80-84ab-11ea-839e-c6cdd524ac4a.png)

You can easily reproduce this by opening the Chrome console and resizing/giving it more and more width.

**Comment by matt-uib** [comment]
@sschmidTU please open for this also an issue at Vexflow .0xfe is active now anyway. Maybe he can easily fix it for us.

**Comment by sschmidTU** [comment]
well, i can, though OSMD calculations probably take less than 1/10th the time of Vexflow rendering (the drawing, not creating objects), so it's probably not the most important thing Vexflow can do for us right now. See [#706 (problems with Vexflow layout versions > 3.0.4)](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/pull/706#issuecomment-617819541).

**Comment by sschmidTU** [comment]
Fixed. Re-render on resize is also (still) very fast, almost seems faster than before.
We now recalculate beams on resize, just like for zoom.

**Comment by sschmidTU** [comment]
This will be in a new release very soon, with Vexflow 3.0.4.

**Comment by MilesMorel** [comment]
Great, thank you!
