### ISSUE TITLE
Bad beaming Sometimes

### ISSUE THREAD

**Issue by djae88** [opensheetmusicdisplay/opensheetmusicdisplay#843]
[forBeamTest.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4998954/forBeamTest.zip)
↑test file

![sibelius](https://user-images.githubusercontent.com/56290540/88883806-23fa5580-d270-11ea-88d1-9ff283cf8ea3.png)
↑Sibelius

![endless](https://user-images.githubusercontent.com/56290540/88883883-53a95d80-d270-11ea-8d04-72536ed02347.png)
↑OSMD(when It's fine)

![sometimes](https://user-images.githubusercontent.com/56290540/88883892-57d57b00-d270-11ea-9b21-f0f99e48ff7b.png)
↑OSMD(sometimes)

I found this when I use `newSystemFromXML: true` and resize the browser larger and reload

**Comment by bneumann** [comment]
Hmmm this looks sort of a vexfow mechanism to me. @sschmidTU are we doint something to control the beams? If you give me a hint I can fix this

**Comment by sschmidTU** [comment]
@djae88 this should be fixed now, can you test this with the current develop build? i've attached it below:

[opensheetmusicdisplay.min.js.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5016596/opensheetmusicdisplay.min.js.zip)

unfortunately i couldn't reproduce the bad beaming, but i can see in the code that this could happen in cases like yours.

**Comment by djae88** [comment]
@sschmidTU 
I tested with current develop build, but theres's still a problem.
![1](https://user-images.githubusercontent.com/56290540/89599667-2cb7e080-d89b-11ea-908f-8f097ad981cf.png)
![2](https://user-images.githubusercontent.com/56290540/89599673-2e81a400-d89b-11ea-9195-dd2ea54b80df.png)

**Comment by sschmidTU** [comment]
not reproducible
